name: One UI 9 Radar

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  radar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install feedparser requests

      - name: Run One UI 9 Radar
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          python oneui9_radar.py

      - name: Save radar history
        run: |
          git config user.name "One UI 9 Radar"
          git config user.email "radar@github.com"

          git add seen.json

          git diff --cached --quiet || \
          git commit -m "Update radar history"

          git push
